version: "3.1"

volumes:
  parse-data:
    driver: local
  mongo-data:
    driver: local
  redis-data:
    driver: local

services:
  parse-server:
    build:.
    restart: always
    volumes:
      - parse-data:/code
    ports:
      - 8080:8080
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
